name: Schedule Build Trigger

on:
  workflow_dispatch: # Manually trigger a workflow run
  schedule:
    - cron: '45 12 * * 6'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update last deploy timestamp
        run: |
          date '+%Y-%m-%dT%H:%M:%SZ' > LAST_DEPLOY

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LAST_DEPLOY
          git commit -m "Update last deploy timestamp"
          git push

      - name: Build hook request
        run: curl -X POST ${{ secrets.BUILD_HOOK }}
